### ISSUE TITLE
mvn install error

### ISSUE THREAD

**Issue by qinkun1234** [Dreampie/resty#1]
mvn install 时候报以下错
![mvn install error](https://38.media.tumblr.com/44a800556273b188d941b2e0069893b0/tumblr_ni0rb3fNZA1sbcvr8o1_1280.jpg)

[INFO] 
[INFO] resty ............................................. SUCCESS [5.836s]
[INFO] resty-log ......................................... SUCCESS [1.939s]
[INFO] resty-cache ....................................... SUCCESS [0.433s]
[INFO] resty-common ...................................... SUCCESS [0.931s]
[INFO] resty-upload ...................................... SUCCESS [0.395s]
[INFO] resty-orm-sql ..................................... SUCCESS [0.719s]
[INFO] resty-security .................................... SUCCESS [0.419s]
[INFO] resty-route ....................................... SUCCESS [0.672s]
[INFO] resty-orm-nosql ................................... SUCCESS [0.250s]
[INFO] resty-client ...................................... SUCCESS [0.404s]
[INFO] resty-example ..................................... FAILURE [0.005s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.146s
[INFO] Finished at: Sun Jan 11 22:02:57 CST 2015
[INFO] Final Memory: 15M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Plugin org.apache.maven.plugins:maven-war-plugin:2.2 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-war-plugin:jar:2.2: 1 problem was encountered while building the effective model
[ERROR] [FATAL] Non-parseable POM /Users/qk/.m2/repository/org/apache/maven/plugins/maven-war-plugin/2.2/maven-war-plugin-2.2.pom: end tag name </form> must match start tag name <input> from line 145 (position: TEXT seen ...<input  type="hidden" name="forceflag" value="">\r\n</form>... @146:8)  @ line 146, column 8
[ERROR] -> [Help 1]

**Comment by Dreampie** [comment]
pom.xml有错误吗？-X 看一下详细的错误

**Comment by qinkun1234** [comment]
已解决:
git checkout v1.0-beta
我切的版本问题。master版本下有这个问题。v1.0-beta是可以运行的。
