### ISSUE TITLE
Release 1.0 使用post请求时的unhandled exception

### ISSUE THREAD

**Issue by hanqo** [Dreampie/Resty#11]
使用1.0snapshot于play framework，执行post操作时，出现unhandled exception。具体如下：
Job DEFAULT.6da64b5bd2ee-d729633d-d859-40b4-8b4d-0f1ff53faec8 threw an unhandled Exception: 
        cn.dreampie.client.exception.ClientException: null
        at cn.dreampie.client.Client.ask(Client.java:57)

其中 post数据是json格式，其中有个parameter是String形式的float数值，叫做"limit":"100.0"，这个值只要是数字形式就一定触发此exception，然而无意间用科学计数存入 limit:"1.0E6"，exception不再出现。后测试其他，只要含字母就不会出现。不太理解其原因。

另外，这个访问url和post json用curl试过，完全没有问题。

**Comment by Dreampie** [comment]
你使用最新的github上的源码也有这问题吗？如果有，你把客户端使用代码和服务端接口代码精简之后发给我，我会尽快帮你解决

**Comment by hanqo** [comment]
多谢回复 

我们项目用的是1.0的 我看最新的API修改了不少 估计项目是暂时不会更新 工作量太大

代码大概是如下
   50     private static ResponseData RestPost(String path, String params) {
   51         Client client = new Client(BASE_PATH);
   52         ClientRequest postRequest = new ClientRequest(path, HttpMethod.POST);
   53         postRequest.addHeader("Content-Type", "application/json; charset=utf-8");
   54         postRequest.setJsonParameter(params);
   55         return client.build(postRequest).ask();
   56     }  

我看报exception的源码是
   48   public ResponseData ask() {
   49     HttpURLConnection conn = null;
   50     try {
   51     ¦ conn = getHttpConnection();
   52     ¦ conn.connect();
   53     ¦ return readResponse(conn);
   54     } catch (Exception e) {
   55     ¦ if (e instanceof ClientException)
   56     ¦   throw (ClientException) e;
   57     ¦ throw new ClientException(e.getMessage(), e);                                                                                                               
   58     } finally {
   59     ¦ if (conn != null) {
   60     ¦   conn.disconnect();
   61     ¦ }
   62     }  
   63   }

57行新throw的exception没有得到handle造成的

**Comment by Dreampie** [comment]
你调试服务器没有，看看服务器报错没有，resty－client是原生的jdk自带的HttpUrlConnection，代码看起来没有问题，你看看服务器收到请求没有，如果服务端收到请求之后解析错误的话，你可以把服务器端接收到的json数据和你发送的时候的json数据先对比一下，客户端的json尽量使用json工具转换对象，晚上我调试一下

**Comment by hanqo** [comment]
又调试了一下，这边服务器端是收到了请求，而且对比和发送的json一样，并且服务器显示返回201创建成功。所以应该就是发送成功，服务器正常响应，发送之后产生了exception。

**Comment by Dreampie** [comment]
1.0的时候没有考虑201状态，你可以自己稍微修改一下源码，最新的代码  进行了不少优化 你也可以测试一下 github上最新的代码有没有问题，如果没有问题 只能推荐你更新一下你的客户端代码了

最近会发布 1.1.0的SNAPSHOT版，有不少改进和bug修复

**Comment by hanqo** [comment]
多谢。源码我修改了一下，还是有问题，可能是我修改的不对，不过我觉得应该就是你说的问题。
如果方便，可否改进一下1.0（加入201支持），或者提供一下1.1的jar文件？我用java不多 对于jar生成费了好大劲，主要是不用eclipse，不太熟悉这些工具。
多谢了！

**Comment by Dreampie** [comment]
现在github上的源码已经修改了，你可以试试能不能满足你的情况。生成jar非常简单，你如果使用maven，mvn install  就安装到本地了，不行的话就到qq 群  364932714  找我要一下

**Comment by hanqo** [comment]
多谢耐心解答 1.1的版本虽然api变动不少 但的确好用很多
