### ISSUE TITLE
请求保存实体（基本参数都有提交），实体为null？，什么原因？

### ISSUE THREAD

**Issue by yovenny** [Dreampie/Resty#12]
![image](https://cloud.githubusercontent.com/assets/8280857/9984375/d779f8b2-6048-11e5-9652-0e850993fb33.png)

**Comment by Dreampie** [comment]
截图控制台的请求参数

**Comment by yovenny** [comment]
请求实体：{content:"test",imgeurl:"http://www.baidu.com",pcount:"4"}

@Dreampie 解答：
                application.properties  中设置app.oneParamParse=true

**Comment by Dreampie** [comment]
在application.properties 添加配置
```
app.oneParamParse=true
```
当只有一个body包裹的参数时(不包括url里的参数)，直接转换为方法需要的参数类型

原因是：
```
method(Type param1,Type param2)

//当有多个json参数请求，需要参数名字来对应参数的位置，如：
//{param1:"json1",param2:"json2"}
//app.oneParamParse=true 的意思是 只有一个json参数时 不需要使用参数名字来对应转换类型
```
