### ISSUE TITLE
cached 拦截器中method失效问题

### ISSUE THREAD

**Issue by zylantian** [Dreampie/Resty#20]
cacheInterceptor中，method失效时间是可以自定义的，但是框架中对于失效时间，例如我method中用到的表更新了，method在缓存中不会失效吧

**Comment by Dreampie** [comment]
method的根据 action 和过期时间 共同作用，如果调用了对数据有影响的操作 如 post delete put等method，缓存会自动失效 除此之外根据时间失效 ，所以为了保证缓存即时最好不要直接修改数据库
