### ISSUE TITLE
jar包依赖问题

### ISSUE THREAD

**Issue by zhouyijiaren** [Dreampie/Resty#23]
我在用resty-demo做实验，把resty-demo中与resty相关的jar包都删掉了，用的源码。但是出现了这种问题
import cn.dreampie.route.core.annotation.API;
import cn.dreampie.route.core.annotation.GET;
error：The import cn.dreampie.route.core.annotation cannot be resolved

**Comment by Dreampie** [comment]
1.1.0 包和1.2.0-SNAPSHOT 有差距，既然看了源码，应该能看到包变化

**Comment by zhouyijiaren** [comment]
那现在我想把resty-route的jar包换成源码，需要怎么用呢？

**Comment by Dreampie** [comment]
mvn install 到本地 或者上传到你自己的私服，具体的操作，查看maven相关教程

**Comment by zhouyijiaren** [comment]
ok
