### ISSUE TITLE
api接口集合处理咨询

### ISSUE THREAD

**Issue by lzqxx** [Dreampie/Resty#24]
从数据库获取列表数据，列表中每条数据都对应有一个json数组详情数据，框架有没有对集合处理的方法？如通过访问2次数据库，1获取列表，2获取列表对应的数组json详情数据，再通过方法左关联组合两组数据形成一组数据，有这类方法吗？就像C#的linq、lambda

**Comment by Dreampie** [comment]
什么是列表数据，什么是json数组详情数据，提供一个简单的数据结构，比如表只存了 title，另外一张表存了 intro等详情，这种分两次查就行，自己实现一个查询和装配的过程
