### ISSUE TITLE
resty-example中SessionResource的 "用户登录"接口得不到数据

### ISSUE THREAD

**Issue by zhouyijiaren** [Dreampie/Resty#25]
用resty-example，发现接口测试都返回null
我在这个“用户登录”接口即login方法中，自己加了logger，输出username和password，发现是null
这是为什么呢？难道是我的接口地址有问题还是少了什么吗？
http://localhost:9090/api/v1.0/sessions
Body：
username:testupdxx
password:123456
rememberMe:false

**Comment by Dreampie** [comment]
怎么传递的参数，使用的方式，提供示例代码

**Comment by zhouyijiaren** [comment]
用chrome的postman插件来测试接口的，用的POST方法


POST /api/v1.0/sessions HTTP/1.1
Host: localhost:9090
Cache-Control: no-cache
Postman-Token: 1eae5ca3-b0bb-fd2a-8a74-1bc2a82c7a7e
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

testupdxx
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

123456
----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="rememberMe"

false
----WebKitFormBoundary7MA4YWxkTrZu0gW

**Comment by Dreampie** [comment]
`Content-Type: multipart/form-data` ？

json的curl 测试
```shell
~ curl -X POST http://localhost/api/v1.0/sessions \
> -H "Content-Type: application/json" \
> -d '{"username":"admin","password":"123","rememberMe":"true"}'
```

**Comment by zhouyijiaren** [comment]
curl是可以，我看看我现在用的postman怎么实现这种类似方式
