### ISSUE TITLE
User和UserInfo的问题

### ISSUE THREAD

**Issue by zhouyijiaren** [Dreampie/Resty#26]
UserInfo的数据是在什么时候获取到的？
是每次获取User的时候就会获取UserInfo吗，我看到 User类中getUserInfos方法并没有被直接调用，这里是怎么调用的呢，是用反射吗，在哪里反射的？

**Comment by Dreampie** [comment]
example中 getUserInfos 上有一行描述，说的是转换json时，默认会认为这是一个属性，会直接提取数据

**Comment by zhouyijiaren** [comment]
是在Model中反射来调用这个getUserInfos吗？

**Comment by zhouyijiaren** [comment]
这个转换json并提取数据的类和配置在哪里啊，就是它是怎么被解释成一个属性的

**Comment by Dreampie** [comment]
getXxx，是java定义的属性，难道不是常识？如果你不想json的时候当属性使用，看那段说明，有说怎么做

**Comment by zhouyijiaren** [comment]
getUserInfos被调用时在fastjson中是吧？

**Comment by Dreampie** [comment]
```java
 //  @JSONField(serialize = false) 如果getXxx的值不转为json  使用该注解
```
描述有这一行

**Comment by zhouyijiaren** [comment]
我知道，看见了，写这个是让他不被调用
所以我想问，getUserInfo能被调用时因为用到了fastjson，是吧？

**Comment by Dreampie** [comment]
嗯 是使用fastjson去转换

**Comment by zhouyijiaren** [comment]
恩  明白了
