### ISSUE TITLE
上传文件的问题

### ISSUE THREAD

**Issue by zhouyijiaren** [Dreampie/Resty#27]
我现在在做上传文件的功能，这时候我的前台数据用的form-data
后台按照介绍里那样设置好了，但是在测试接口时，显示不能使用form-data,请问我要怎么来上传呢，不能还用json吧？

**Comment by Dreampie** [comment]
把代码和错误发出来看看

**Comment by zhouyijiaren** [comment]
不好意思，是我以前在Header中添加了Content-Type:application/json这个，去掉以后就没事了

**Comment by Dreampie** [comment]
嗯
