### ISSUE TITLE
Resty怎么获取Session？

### ISSUE THREAD

**Issue by jiangjunfeng98** [Dreampie/Resty#29]
调试的时候debugger里面可以this.getRequest().request.getSession().getAttributeNames()获取，
![1](https://cloud.githubusercontent.com/assets/12987428/15771719/3668f420-299f-11e6-9e14-2a2a3f3a772b.jpg)

但是代码里this.getRequest()里面没有request，这个时候我该怎么获取Session呢？

![image](https://cloud.githubusercontent.com/assets/12987428/15771640/bedf9a6c-299e-11e6-988d-bfa42a7eb6e4.png)

**Comment by Dreampie** [comment]
resty提供了分布式的session，Subject对象来操作，如果要获取原生的request对象,使用 `unwrap` 方法

```java
public <T> T unwrap(Class<T> clazz) {
    if (clazz == HttpServletRequest.class || clazz == ServletRequest.class) {
      return (T) request;
    }
    throw new IllegalArgumentException("underlying implementation is HttpServletRequest, not " + clazz.getName());
  }
```

**Comment by jiangjunfeng98** [comment]
谢谢，解决了
