### ISSUE TITLE
Resty的单点登录问题

### ISSUE THREAD

**Issue by jiangjunfeng98** [Dreampie/Resty#30]
如果我使用了单点登录，这个时候我只能拿到用户除密码外的信息，如何达到Subject.login的效果，能不能跳过密码验证直接写入username？
![image](https://cloud.githubusercontent.com/assets/12987428/15771817/cc9c95be-299f-11e6-8245-b3a5ef450dce.png)

**Comment by Dreampie** [comment]
嗯，直接通过用户名授权登录的话，有一个私有方法，可以开放出来，是直接通过用户名认证的，但是你必须自己判断用户名存不存在行吗？

**Comment by jiangjunfeng98** [comment]
授权这个我在AuthenticateService的getPrincipal设置了一个固定值，可以通过。但是Subject.current()的返回值为空
代码段：
![image](https://cloud.githubusercontent.com/assets/12987428/15773560/25ef3900-29aa-11e6-85e0-46479e3a2b7f.png)

错误：
![image](https://cloud.githubusercontent.com/assets/12987428/15773537/0636e9a0-29aa-11e6-8982-d4a88138ca47.png)

**Comment by Dreampie** [comment]
也就是说你没有经过SecurityInterceptor，凡是经过这个拦截器的 都必然会产生一个session，你是怎么实现的

**Comment by jiangjunfeng98** [comment]
单点后直接调用Subject.login

**Comment by Dreampie** [comment]
怎么单点的  不是通过一个接口跳过来？

**Comment by jiangjunfeng98** [comment]
解决了，通过js请求登录一次，以前直接在jsp调用了Subject.login，Session就是空的
