### ISSUE TITLE
登录成功后credentials里面添加的路径依然不能访问并且tomcat报错，credentials.add(new Credential("*", "/api/v1.0/users/**", "users"))

### ISSUE THREAD

**Issue by kqs203** [Dreampie/Resty#34]
# **credentials.add(new Credential("*", "/api/v1.0/users/**", "users"))初次访问时，**postman测试工具显示
status: 401 Unauthorized   body里面显示Unauthorized，http://localhost:8088/resty/api/v1.0/sessions输入正确的用户名密码后 body显示当前登录用户的详细信息，此时登录成功
再次访问http://localhost:8088/resty/api/v1.0/users    显示500 Internal Server Error, body里面什么都不显示，
# tomcat 里的错误信息如下

16-06-07 16:55:11.363 [http-apr-8088-exec-34] INFO  cn.dreampie.route.core.Route - 

Match route ----------------- 2016-06-07 16:55:11 ------------------------------
Resource     : cn.dreampie.resource.user.UserResource(UserResource.java:29)
Method       : findAll
PathPattern  : GET /api1.0/users
ContentType  : null
PathParams   : 
ReturnType   : java.util.List<cn.dreampie.resource.user.model.User>
Interceptors : cn.dreampie.route.cache.CacheInterceptor(CacheInterceptor.java:36)
               cn.dreampie.route.interceptor.security.SecurityInterceptor(SecurityInterceptor.java:29)
               cn.dreampie.route.interceptor.transaction.TransactionInterceptor(TransactionInterceptor.java:21)
--------------------------------------------------------------------------------

```java
16-06-07 16:55:11.364 [http-apr-8088-exec-34] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_http::/users}, key: {/users}
16-06-07 16:55:11.364 [http-apr-8088-exec-34] DEBUG cn.dreampie.cache.SimpleCache - Miss, group: {_http::/users}, key: {/api1.0/users}
16-06-07 16:55:11.364 [http-apr-8088-exec-34] DEBUG cn.dreampie.security.SessionBuilder - Session key was: 811d5d3b-8ac4-4d5e-8e77-76743fe65683.
16-06-07 16:55:11.364 [http-apr-8088-exec-34] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_session}, key: {811d5d3b-8ac4-4d5e-8e77-76743fe65683}
16-06-07 16:55:11.364 [http-apr-8088-exec-34] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_session}, key: {testhttp-apr-8080-exec-10}
16-06-07 16:55:11.364 [http-apr-8088-exec-34] DEBUG net.sf.ehcache.store.disk.Segment - put added 0 on heap
16-06-07 16:55:11.366 [http-apr-8088-exec-34] DEBUG net.sf.ehcache.store.disk.Segment - put updated, deleted 0 on heap
16-06-07 16:55:11.367 [http-apr-8088-exec-34] DEBUG net.sf.ehcache.store.disk.Segment - put updated, deleted 0 on disk
16-06-07 16:55:11.367 [http-apr-8088-exec-34] DEBUG cn.dreampie.security.SessionBuilder - Found session success, username was: testhttp-apr-8080-exec-10.
16-06-07 16:55:11.367 [http-apr-8088-exec-34] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_credential}, key: {_allCredentials}
16-06-07 16:55:11.367 [http-apr-8088-exec-34] INFO  cn.dreampie.security.Subject - GET /api1.0/users need credential users
16-06-07 16:55:11.367 [http-apr-8088-exec-34] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_principal}, key: {testhttp-apr-8080-exec-10}
16-06-07 16:55:11.367 [_session.data] DEBUG net.sf.ehcache.store.disk.Segment - fault removed 0 from heap
16-06-07 16:55:11.367 [_session.data] DEBUG net.sf.ehcache.store.disk.Segment - fault added 0 on disk
16-06-07 16:55:11.372 [http-apr-8088-exec-34] WARN  cn.dreampie.route.holder.DefaultExceptionHolder - Request "GET /api1.0/users" error : 400 null
java.lang.NullPointerException: null
	at cn.dreampie.security.Principal.hasCredential(Principal.java:50) ~[Principal.class:na]
	at cn.dreampie.security.Subject.check(Subject.java:217) ~[Subject.class:na]
	at cn.dreampie.route.interceptor.security.SecurityInterceptor.intercept(SecurityInterceptor.java:35) ~[SecurityInterceptor.class:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:54) ~[RouteInvocation.class:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:189) ~[RouteInvocation.class:na]
	at cn.dreampie.route.cache.CacheInterceptor.intercept(CacheInterceptor.java:69) ~[CacheInterceptor.class:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:54) ~[RouteInvocation.class:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:189) ~[RouteInvocation.class:na]
	at cn.dreampie.route.core.RouteHandler.handle(RouteHandler.java:67) ~[RouteHandler.class:na]
	at cn.dreampie.route.handler.cors.CORSHandler.handle(CORSHandler.java:102) ~[CORSHandler.class:na]
	at cn.dreampie.route.RestyFilter.doFilter(RestyFilter.java:82) ~[RestyFilter.class:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.52]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.52]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.0.13.jar:1.0.13]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.52]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.52]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.52]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) [catalina.jar:7.0.52]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.52]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.52]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040) [tomcat-coyote.jar:7.0.52]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) [tomcat-coyote.jar:7.0.52]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2441) [tomcat-coyote.jar:7.0.52]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2430) [tomcat-coyote.jar:7.0.52]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]


```

**Comment by Dreampie** [comment]
```java
16-06-07 16:55:11.372 [http-apr-8088-exec-34] WARN  cn.dreampie.route.holder.DefaultExceptionHolder - Request "GET /api1.0/users" error : 400 null
```
url有问题啊

**Comment by kqs203** [comment]
改对了以后还是这样

**Comment by kqs203** [comment]
16-06-07 18:35:16.595 [http-apr-8088-exec-5] INFO  cn.dreampie.route.core.Route - 

Match route ----------------- 2016-06-07 18:35:16 ------------------------------
Resource     : cn.dreampie.resource.user.UserResource(UserResource.java:29)
Method       : findAll
PathPattern  : GET /api/v1.0/users
ContentType  : null
PathParams   : 
ReturnType   : java.util.List<cn.dreampie.resource.user.model.User>
Interceptors : cn.dreampie.route.cache.CacheInterceptor(CacheInterceptor.java:36)
               cn.dreampie.route.interceptor.security.SecurityInterceptor(SecurityInterceptor.java:29)
               cn.dreampie.route.interceptor.transaction.TransactionInterceptor(TransactionInterceptor.java:21)
--------------------------------------------------------------------------------

16-06-07 18:35:16.595 [http-apr-8088-exec-5] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_http::/users}, key: {/users}
16-06-07 18:35:16.595 [http-apr-8088-exec-5] DEBUG cn.dreampie.cache.SimpleCache - Miss, group: {_http::/users}, key: {/api/v1.0/users}
16-06-07 18:35:16.595 [http-apr-8088-exec-5] DEBUG cn.dreampie.security.SessionBuilder - Session key was: 811d5d3b-8ac4-4d5e-8e77-76743fe65683.
16-06-07 18:35:16.595 [http-apr-8088-exec-5] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_session}, key: {811d5d3b-8ac4-4d5e-8e77-76743fe65683}
16-06-07 18:35:16.596 [http-apr-8088-exec-5] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_session}, key: {testhttp-apr-8080-exec-10}
16-06-07 18:35:16.596 [http-apr-8088-exec-5] DEBUG net.sf.ehcache.store.disk.Segment - put added 0 on heap
16-06-07 18:35:16.597 [http-apr-8088-exec-5] DEBUG net.sf.ehcache.store.disk.Segment - put updated, deleted 0 on heap
16-06-07 18:35:16.597 [http-apr-8088-exec-5] DEBUG net.sf.ehcache.store.disk.Segment - put updated, deleted 0 on disk
16-06-07 18:35:16.597 [http-apr-8088-exec-5] DEBUG cn.dreampie.security.SessionBuilder - Found session success, username was: testhttp-apr-8080-exec-10.
16-06-07 18:35:16.597 [http-apr-8088-exec-5] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_credential}, key: {_allCredentials}
16-06-07 18:35:16.597 [http-apr-8088-exec-5] INFO  cn.dreampie.security.Subject - GET /api/v1.0/users need credential users
16-06-07 18:35:16.598 [http-apr-8088-exec-5] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_principal}, key: {testhttp-apr-8080-exec-10}
16-06-07 18:35:16.598 [_session.data] DEBUG net.sf.ehcache.store.disk.Segment - fault removed 0 from heap
16-06-07 18:35:16.598 [_session.data] DEBUG net.sf.ehcache.store.disk.Segment - fault added 0 on disk
16-06-07 18:35:16.600 [http-apr-8088-exec-5] WARN  cn.dreampie.route.holder.DefaultExceptionHolder - Request "GET /api/v1.0/users" error : 400 null
java.lang.NullPointerException: null
	at cn.dreampie.security.Principal.hasCredential(Principal.java:50) ~[Principal.class:na]
	at cn.dreampie.security.Subject.check(Subject.java:217) ~[Subject.class:na]
	at cn.dreampie.route.interceptor.security.SecurityInterceptor.intercept(SecurityInterceptor.java:35) ~[SecurityInterceptor.class:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:54) ~[RouteInvocation.class:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:189) ~[RouteInvocation.class:na]
	at cn.dreampie.route.cache.CacheInterceptor.intercept(CacheInterceptor.java:69) ~[CacheInterceptor.class:na]
	at cn.dreampie.route.core.RouteInvocation.methodInvoke(RouteInvocation.java:54) ~[RouteInvocation.class:na]
	at cn.dreampie.route.core.RouteInvocation.invoke(RouteInvocation.java:189) ~[RouteInvocation.class:na]
	at cn.dreampie.route.core.RouteHandler.handle(RouteHandler.java:67) ~[RouteHandler.class:na]
	at cn.dreampie.route.handler.cors.CORSHandler.handle(CORSHandler.java:102) ~[CORSHandler.class:na]
	at cn.dreampie.route.RestyFilter.doFilter(RestyFilter.java:82) ~[RestyFilter.class:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.52]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.52]
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123) [druid-1.0.13.jar:1.0.13]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) [catalina.jar:7.0.52]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) [catalina.jar:7.0.52]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170) [catalina.jar:7.0.52]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:98) [catalina.jar:7.0.52]
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950) [catalina.jar:7.0.52]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) [catalina.jar:7.0.52]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408) [catalina.jar:7.0.52]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040) [tomcat-coyote.jar:7.0.52]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607) [tomcat-coyote.jar:7.0.52]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2441) [tomcat-coyote.jar:7.0.52]
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2430) [tomcat-coyote.jar:7.0.52]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]

**Comment by kqs203** [comment]
是不是对jdk版本与tomcat版本有要求

**Comment by Dreampie** [comment]
jdk1.6+tomcat6就行

看看你的AppConfig类 怎么写的

**Comment by kqs203** [comment]
package cn.dreampie.config;

import cn.dreampie.orm.ActiveRecordPlugin;
import cn.dreampie.orm.provider.c3p0.C3p0DataSourceProvider;
import cn.dreampie.orm.provider.druid.DruidDataSourceProvider;
import cn.dreampie.route.cache.CacheInterceptor;
import cn.dreampie.route.config.*;
import cn.dreampie.route.handler.cors.CORSHandler;
import cn.dreampie.route.interceptor.security.SecurityInterceptor;
import cn.dreampie.route.interceptor.transaction.TransactionInterceptor;
import com.alibaba.fastjson.serializer.SerializerFeature;

/**
 * Created by ice on 14-12-29.
 */
public class AppConfig extends Config {

  public void configConstant(ConstantLoader constantLoader) {
    //通过后缀来返回不同的数据类型  你可以自定义自己的  render  如：FreemarkerRender
    //constantLoader.addRender("json", new JsonRender());
    constantLoader.addJsonSerializerFeature(SerializerFeature.WriteNullStringAsEmpty);
  }

  public void configResource(ResourceLoader resourceLoader) {
    //设置resource的目录  减少启动扫描目录
//    resourceLoader.addExcludePackages("cn.dreampie.resource");
    resourceLoader.addIncludePackages("cn.dreampie.resource");
  }

  public void configPlugin(PluginLoader pluginLoader) {
//    //第一个数据库
    C3p0DataSourceProvider cdsp = new C3p0DataSourceProvider("default");
    ActiveRecordPlugin activeRecordCdsp = new ActiveRecordPlugin(cdsp);
    activeRecordCdsp.addIncludePackages("cn.dreampie.resource");
    pluginLoader.add(activeRecordCdsp);
//
//    //第二个数据库
    DruidDataSourceProvider ddsp = new DruidDataSourceProvider("demo");
    ActiveRecordPlugin activeRecordDdsp = new ActiveRecordPlugin(ddsp);
//    activeRecordDdsp.addIncludePackages("cn.dreampie.demo"); 只是测试 没有具体的包有该数据源的对象
    pluginLoader.add(activeRecordDdsp);

    //读写分离
//    DruidDataSourceProvider writeDsp = new DruidDataSourceProvider("write");
//    DruidDataSourceProvider readDsp = new DruidDataSourceProvider("read");
//    ActiveRecordPlugin activeRecordDdsp = new ActiveRecordPlugin("readwrite", writeDsp, readDsp);
//    activeRecordDdsp.addIncludePackages("cn.dreampie.resource");
//    pluginLoader.add(activeRecordDdsp);

//    pluginLoader.add(new SpringPlugin(HelloApp.class));
//    JndiDataSourceProvider jdsp = new JndiDataSourceProvider("jndiDs", "jndiName");
//    ActiveRecordPlugin activeRecordJdsp = new ActiveRecordPlugin(jdsp);
//    pluginLoader.add(activeRecordJdsp);
  }

  public void configInterceptor(InterceptorLoader interceptorLoader) {
    //缓存
    interceptorLoader.add(new CacheInterceptor());
    //权限拦截器
    interceptorLoader.add(new SecurityInterceptor(new MyAuthenticateService()));
    //事务的拦截器 @Transaction
    interceptorLoader.add(new TransactionInterceptor());
  }

  public void configHandler(HandlerLoader handlerLoader) {
    //跨域
    handlerLoader.add(new CORSHandler("GET,POST,PUT,DELETE"));
  }
}

**Comment by kqs203** [comment]
没改过什么东西啊

**Comment by Dreampie** [comment]
MyAuthenticateService  呢

**Comment by kqs203** [comment]
package cn.dreampie.config;

import cn.dreampie.log.Logger;
import cn.dreampie.resource.user.model.User;
import cn.dreampie.security.AuthenticateService;
import cn.dreampie.security.PasswordService;
import cn.dreampie.security.Principal;
import cn.dreampie.security.credential.Credential;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Created by ice on 15-1-7.
 */
public class MyAuthenticateService extends AuthenticateService {
    //private static final Logger logger = Logger.getLogger(MyAuthenticateService.class);
    private XyPasswordService defaultPasswordService = new XyPasswordService();
  /*public PasswordService getPasswordService() {
    return super.getPasswordService();
  }*/
  public PasswordService getPasswordService() {
      return defaultPasswordService;
  }
  /**
   * 查询用户信息  这儿new一个用户对象来模拟
   *
   * @param username 登录的用户名
   * @return 用户权限对象
   */
  public Principal getPrincipal(String username) {
    PasswordService passwordService = getPasswordService();

    /*User u = new User().set("username", username).set("password", passwordService.crypto("123", "x")).put("permissions", new HashSet<String>() {{
      add("users");
    }});*/
      Principal<User> principal=null;
      User u=null;
      List<User> ulist = User.dao.findBy("username=?", username);
      if(ulist.size()>0){
          u=ulist.get(0);
      }
      if (u != null) {
          principal = new Principal<User>(u.<String>get("username"), u.<String>get("password"), null, u);
      }
    //Principal<User> principal = new Principal<User>(u.<String>get("username"), u.<String>get("password"), "x", (Set) u.get("permissions"), u);
    return principal;
  }

  /**
   * 加载全部的权限信息
   *
   * @return 权限集合
   */
  public Set<Credential> getAllCredentials() {
    Set<Credential> credentials = new HashSet<Credential>();
    credentials.add(new Credential("*", "/api/v1.0/users/**", "users"));
      credentials.add(new Credential("*", "/stest/**", "stest"));
      return credentials;
  }
}

**Comment by kqs203** [comment]
也就把密码验证变成不需要转码，直接拿出比较

**Comment by kqs203** [comment]
sessionsource登录方法类



package cn.dreampie.resource;

import cn.dreampie.resource.user.model.User;
import cn.dreampie.route.annotation.API;
import cn.dreampie.route.annotation.DELETE;
import cn.dreampie.route.annotation.POST;
import cn.dreampie.security.Subject;

/**
 * Created by wangrenhui on 15/1/10.
 */
@API("/sessions")
public class SessionResource extends ApiResource {


  @POST(des = "用户登录")
  public User login(String username, String password, boolean rememberMe) {
    Subject.login(username, password);
    return (User) Subject.getPrincipal().getModel();
  }

  @DELETE(des = "用户退出")
  public void logout() {
    Subject.logout();
  }
}

**Comment by Dreampie** [comment]
Principal  第三个参数 是权限列表  如果null的话 就验证不了权限

**Comment by Dreampie** [comment]
代码  高亮 
````java`
`````

**Comment by Dreampie** [comment]
principal = new Principal<User>(u.<String>get("username"), u.<String>get("password"), new HashSet<String>(), u);

**Comment by kqs203** [comment]
我试一下

**Comment by kqs203** [comment]
Set<String> credentials = new HashSet<String>();
      credentials.add("/api/v1.0/users/** ");
      credentials.add("/stest/**");


      if(ulist.size()>0){
          u=ulist.get(0);
      }
      if (u != null) {
          principal = new Principal<User>(u.<String>get("username"), u.<String>get("password"), credentials, u);
      }

加上这段代码后登录成功后访问/api/v1.0/users
显示status 403 Forbidden   ,而且stest的servlet不管登录与否都能访问

**Comment by kqs203** [comment]
stest的servlet每次访问都会增加一条记录在mysql表里面

**Comment by Dreampie** [comment]
403 对的啊  你没有给这个用户权限 他就不能访问 

web.xml 看看

**Comment by kqs203** [comment]
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://java.sun.com/xml/ns/javaee"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
         version="2.5">
  <display-name>Archetype Created Web Application</display-name>

  
  <filter>
    <filter-name>DruidWebStatFilter</filter-name>
    <filter-class>com.alibaba.druid.support.http.WebStatFilter</filter-class>
    <init-param>
      <param-name>exclusions</param-name>
      <param-value>*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*</param-value>
    </init-param>
    <init-param>
      <param-name>profileEnable</param-name>
      <param-value>true</param-value>
    </init-param>
  </filter>

  <filter-mapping>
    <filter-name>DruidWebStatFilter</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>

  <servlet>
    <servlet-name>DruidStatView</servlet-name>
    <servlet-class>com.alibaba.druid.support.http.StatViewServlet</servlet-class>
    <init-param>
      <param-name>loginUsername</param-name>
      <param-value>admin</param-value>
    </init-param>

    <init-param>
      <param-name>loginPassword</param-name>
      <param-value>admin</param-value>
    </init-param>
  </servlet>

  <servlet-mapping>
    <servlet-name>DruidStatView</servlet-name>
    <url-pattern>/druid/*</url-pattern>
  </servlet-mapping>

  <filter>
    <filter-name>RestyFilter</filter-name>
    <filter-class>cn.dreampie.route.RestyFilter</filter-class>
    <init-param>
      <param-name>exclusions</param-name>
      <param-value>/**/*.js,/**/*.gif,/**/*.jpg,/**/*.png,/**/*.css,/**/*.ico,/druid/**</param-value>
    </init-param>
    <init-param>
      <param-name>configClass</param-name>
      <param-value>cn.dreampie.config.AppConfig</param-value>
    </init-param>
  </filter>
  <filter-mapping>
    <filter-name>RestyFilter</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>


  <servlet>
    <servlet-name>TestServlet</servlet-name>
    <servlet-class>cn.dreampie.resource.TestServlet</servlet-class>
  </servlet>
  <servlet-mapping>
    <servlet-name>TestServlet</servlet-name>
    <url-pattern>/stest</url-pattern>
  </servlet-mapping>
</web-app>

**Comment by kqs203** [comment]
为什么*号都不见了   <web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://java.sun.com/xml/ns/javaee"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
         version="2.5">
  <display-name>Archetype Created Web Application</display-name>

  
  <filter>
    <filter-name>DruidWebStatFilter</filter-name>
    <filter-class>com.alibaba.druid.support.http.WebStatFilter</filter-class>
    <init-param>
      <param-name>exclusions</param-name>
      <param-value>*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*</param-value>
    </init-param>
    <init-param>
      <param-name>profileEnable</param-name>
      <param-value>true</param-value>
    </init-param>
  </filter>

  <filter-mapping>
    <filter-name>DruidWebStatFilter</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>

  <servlet>
    <servlet-name>DruidStatView</servlet-name>
    <servlet-class>com.alibaba.druid.support.http.StatViewServlet</servlet-class>
    <init-param>
      <param-name>loginUsername</param-name>
      <param-value>admin</param-value>
    </init-param>

    <init-param>
      <param-name>loginPassword</param-name>
      <param-value>admin</param-value>
    </init-param>
  </servlet>

  <servlet-mapping>
    <servlet-name>DruidStatView</servlet-name>
    <url-pattern>/druid/*</url-pattern>
  </servlet-mapping>

  <filter>
    <filter-name>RestyFilter</filter-name>
    <filter-class>cn.dreampie.route.RestyFilter</filter-class>
    <init-param>
      <param-name>exclusions</param-name>
      <param-value>/**/*.js,/**/*.gif,/**/*.jpg,/**/*.png,/**/*.css,/**/*.ico,/druid/**</param-value>
    </init-param>
    <init-param>
      <param-name>configClass</param-name>
      <param-value>cn.dreampie.config.AppConfig</param-value>
    </init-param>
  </filter>
  <filter-mapping>
    <filter-name>RestyFilter</filter-name>
    <url-pattern>/*</url-pattern>
  </filter-mapping>


  <servlet>
    <servlet-name>TestServlet</servlet-name>
    <servlet-class>cn.dreampie.resource.TestServlet</servlet-class>
  </servlet>
  <servlet-mapping>
    <servlet-name>TestServlet</servlet-name>
    <url-pattern>/stest</url-pattern>
  </servlet-mapping>
</web-app>

**Comment by Dreampie** [comment]
你的编辑器左下角有教程先读读

**Comment by kqs203** [comment]
权限列表是在数据库的permission表里增加吗，那还得增加实体类了吧

**Comment by Dreampie** [comment]
嗯  具体的你可以看看  resty-demo项目

**Comment by kqs203** [comment]
答主好厉害，你是框架作者吗

**Comment by Dreampie** [comment]
嗯  你先了解github 的markdown的用法，还有权限部分 添加时应该是权限对应的key
```java
Set<String> credentials = new HashSet<String>();
      credentials.add("users");
      credentials.add("stest");


      if(ulist.size()>0){
          u=ulist.get(0);
      }
      if (u != null) {
          principal = new Principal<User>(u.<String>get("username"), u.<String>get("password"), credentials, u);
      }
```

**Comment by kqs203** [comment]
好的，非常感谢

**Comment by kqs203** [comment]
resty-demo项目地址是哪个，没找到啊

**Comment by kqs203** [comment]
不好意思，对github不熟，现在已经找到了

**Comment by kqs203** [comment]
为什么我从demo拷了一部分代码到我的example项目，登录成功后，可以访问users链接，但是调用logout方法一直注销失败呢？退出登录还需要做其他设置吧

**Comment by 1557100211** [comment]
我的也是这个问题，按照上面的方法提示Password not match；密码不是没有加密么。我数据库存放的就是123456啊。

**Comment by Dreampie** [comment]
用DefaultPasswordService 加密存储

**Comment by 1557100211** [comment]
`@Test
	public void genPassword() {
		PasswordService instance = DefaultPasswordService.instance();
		String crypto = instance.crypto("123456");
		System.out.println(crypto);
	}`
是不是我加密的方法不对

**Comment by Dreampie** [comment]
调试 https://github.com/Dreampie/Resty/blob/master/resty-security/src/main/java/cn/dreampie/security/Subject.java 里的login方法，密码match的地方看看密码是不是一致的，是不是走了salt什么的

**Comment by 1557100211** [comment]
为什么我在代码里使用账号密码登陆了一次，再用浏览器访问api，浏览器就不用登录了，直接进去了。。。不需要什么验证么。

**Comment by Dreampie** [comment]
需不需要权限验证 全凭你自己在 AuthService里的设置

**Comment by 1557100211** [comment]
`public class MyAuthenticateService extends AuthenticateService {
	public PasswordService getPasswordService() {
		return super.getPasswordService();
	}

	/**
	 * 查询用户信息 这儿new一个用户对象来模拟
	 *
	 * @param username
	 *            登录的用户名
	 * @return 用户权限对象
	 */
	// public Principal getPrincipal(String username) {
	// PasswordService passwordService = getPasswordService();
	// User u = new User().set("username", username)
	// .set("password", passwordService.crypto("123", "x"))
	// .put("permissions", new HashSet<String>() {
	// {
	// add("users");
	// }
	// });
	//
	// Principal<User> principal = new Principal<User>(
	// u.<String> get("username"), u.<String> get("password"), "x",
	// (Set) u.get("permissions"), u);
	// return principal;
	// }

	public Principal getPrincipal(String username) {
		PasswordService passwordService = getPasswordService();

		/*
		 * User u = new User().set("username", username).set("password",
		 * passwordService.crypto("123", "x")).put("permissions", new
		 * HashSet<String>() {{ add("users"); }});
		 */
		Set<String> credentials = new HashSet<String>();
		credentials.add("users");
		credentials.add("news");
		Principal<User> principal = null;
		User u = null;
		List<User> ulist = User.dao.findBy("username=?", username);
		if (ulist.size() > 0) {
			u = ulist.get(0);
		}
		if (u != null) {
			principal = new Principal<User>(u.<String> get("username"),
					u.<String> get("password"), credentials, u);
		}
		// Principal<User> principal = new
		// Principal<User>(u.<String>get("username"), u.<String>get("password"),
		// "x", (Set) u.get("permissions"), u);
		return principal;
	}

	/**
	 * 加载全部的权限信息
	 *
	 * @return 权限集合
	 */
	public Set<Credential> getAllCredentials() {
		Set<Credential> credentials = new HashSet<Credential>();
		credentials.add(new Credential("*", "/api/v1.0/users/**", "users"));
		credentials.add(new Credential("*", "/api/v1.0/news/**", "news"));
		return credentials;
	}

	@POST
	public User login(String username, String password, boolean rememberMe) {
		Subject.login(username, password, rememberMe);
		return (User) Subject.getPrincipal().getModel();
	}

	@DELETE
	public boolean logout() {
		Subject.logout();
		return true;
	}
}
`

**Comment by 1557100211** [comment]
是不是我写的有问题

**Comment by Dreampie** [comment]
代码看起来没有问题，你把浏览器的cookie清理之后试试

**Comment by 1557100211** [comment]
换个浏览器也是，只要代码中测试登录后都会直接访问到API

**Comment by Dreampie** [comment]
那你的意思  只要代码没有测试登录  访问就出403？

**Comment by 1557100211** [comment]
"Unauthorized"

**Comment by Dreampie** [comment]
你代码在哪儿测试？

**Comment by 1557100211** [comment]
API对外开放的时候，怎么进行权限验证；我和另一个PHP系统对接他怎么访问我的接口？

**Comment by 1557100211** [comment]
`public class TestClient {
	private Client client;

	@Before
	public void setUp() {
		client = new Client("http://localhost:8080/dts/api/v1.0", "/sessions",
				new ClientUser("admin", "123456", false));
	}

	@Test
	public void testApi() {
		ClientRequest clientRequest = new ClientRequest("/news");
		ClientResult clientResult = client.build(clientRequest).get();
		System.out.println("##############"+clientResult);

	}

	@Test
	public void genPassword() {
		PasswordService instance = DefaultPasswordService.instance();
		String crypto = instance.crypto("123456");
		System.out.println(crypto);
	}

}
`

**Comment by Dreampie** [comment]
查看ClientTest里的测试代码

**Comment by Dreampie** [comment]
日志打印出来，看看 session 打出的日志是什么

**Comment by 1557100211** [comment]
好的，我一会试试

**Comment by Dreampie** [comment]
专门开一个问题，说明你的情况

**Comment by 1557100211** [comment]
OK
