### ISSUE TITLE
resty 使用权限访问API时，使用登陆测试代码后，浏览器访问就不用登陆就可访问API

### ISSUE THREAD

**Issue by 1557100211** [Dreampie/Resty#35]
'''
package cn.dreampie.config;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import cn.dreampie.resource.user.model.User;
import cn.dreampie.route.annotation.DELETE;
import cn.dreampie.route.annotation.POST;
import cn.dreampie.security.AuthenticateService;
import cn.dreampie.security.PasswordService;
import cn.dreampie.security.Principal;
import cn.dreampie.security.Subject;
import cn.dreampie.security.credential.Credential;

/**
 * Created by ice on 15-1-7.
 */
public class MyAuthenticateService extends AuthenticateService {
	public PasswordService getPasswordService() {
		return super.getPasswordService();
	}

	/**
	 * 查询用户信息 这儿new一个用户对象来模拟
	 *
	 * @param username
	 *            登录的用户名
	 * @return 用户权限对象
	 */
	// public Principal getPrincipal(String username) {
	// PasswordService passwordService = getPasswordService();
	// User u = new User().set("username", username)
	// .set("password", passwordService.crypto("123", "x"))
	// .put("permissions", new HashSet<String>() {
	// {
	// add("users");
	// }
	// });
	//
	// Principal<User> principal = new Principal<User>(
	// u.<String> get("username"), u.<String> get("password"), "x",
	// (Set) u.get("permissions"), u);
	// return principal;
	// }

	public Principal getPrincipal(String username) {
		PasswordService passwordService = getPasswordService();

		/*
		 * User u = new User().set("username", username).set("password",
		 * passwordService.crypto("123", "x")).put("permissions", new
		 * HashSet<String>() {{ add("users"); }});
		 */
		Set<String> credentials = new HashSet<String>();
		credentials.add("users");
		credentials.add("news");
		Principal<User> principal = null;
		User u = null;
		List<User> ulist = User.dao.findBy("username=?", username);
		if (ulist.size() > 0) {
			u = ulist.get(0);
		}
		if (u != null) {
			principal = new Principal<User>(u.<String> get("username"),
					u.<String> get("password"), credentials, u);
		}
		// Principal<User> principal = new
		// Principal<User>(u.<String>get("username"), u.<String>get("password"),
		// "x", (Set) u.get("permissions"), u);
		return principal;
	}

	/**
	 * 加载全部的权限信息
	 *
	 * @return 权限集合
	 */
	public Set<Credential> getAllCredentials() {
		Set<Credential> credentials = new HashSet<Credential>();
		credentials.add(new Credential("*", "/api/v1.0/users/**", "users"));
		credentials.add(new Credential("*", "/api/v1.0/news/**", "news"));
		return credentials;
	}

	@POST
	public User login(String username, String password, boolean rememberMe) {
		Subject.login(username, password, rememberMe);
		return (User) Subject.getPrincipal().getModel();
	}

	@DELETE
	public boolean logout() {
		Subject.logout();
		return true;
	}
}

'''

**Comment by 1557100211** [comment]
`
@Before
	public void setUp() {
		client = new Client("http://localhost:8080/dts/api/v1.0", "/sessions",
				new ClientUser("admin", "123456", false));
	}

	@Test
	public void testApi() {
		ClientRequest clientRequest = new ClientRequest("/news");
		
		ClientResult clientResult = client.build(clientRequest).get();
		System.out.println("##############"+clientResult);

	}
`

**Comment by 1557100211** [comment]
测试了下，如果我关闭缓存，这个问题就会消失，我发现日志打印的时候，开启缓存的时候只要我测试过登陆后的API，在浏览器访问的时候总会命中API接口。关闭缓存的时候MISS。

**Comment by 1557100211** [comment]
关闭缓存
```
16-06-13 11:14:05.698 [http-8080-2] DEBUG cn.dreampie.security.SessionBuilder - Session key was: fda10ead-b6b9-4ad8-adeb-b5fef6c9bcb2.
16-06-13 11:14:05.698 [http-8080-2] DEBUG cn.dreampie.cache.SimpleCache - Miss, group: {_session}, key: {fda10ead-b6b9-4ad8-adeb-b5fef6c9bcb2}
16-06-13 11:14:05.698 [http-8080-2] WARN  cn.dreampie.security.SessionBuilder - Invalid user session, ignoring this session.
16-06-13 11:14:05.698 [http-8080-2] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_credential}, key: {_allCredentials}
16-06-13 11:14:05.698 [http-8080-2] INFO  cn.dreampie.security.Subject - GET /api/v1.0/news need credential news
16-06-13 11:14:05.698 [http-8080-2] WARN  cn.dreampie.route.holder.DefaultExceptionHolder - Request "GET /api/v1.0/news" error : 401 "Unauthorized"
```
开启缓存
```
16-06-13 11:18:02.954 [http-8080-2] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_http::/news}, key: {/news}
16-06-13 11:18:02.954 [http-8080-2] DEBUG cn.dreampie.cache.SimpleCache - Hit, group: {_http::/news}, key: {/api/v1.0/news}
```

**Comment by Dreampie** [comment]
你AppConfig把SecurityInterceptor放在CacheIntrceptor前面试试

**Comment by 1557100211** [comment]
可以的，这种有权限的API别的系统怎么来访问。其他系统不是JAVA。

**Comment by Dreampie** [comment]
有权限的地方就需要登录，先访问登录接口进行登陆，cookie／responseHeader里有session的token，把session的token带上去访问接口就可以了，SecurityInterceptor 有个构造是sessionBuilder，使用BothXX／TokenXX的sessionbuilder 支持从request Header里读取Token值进行验证

**Comment by Dreampie** [comment]
或者模拟resty-client的方式实现一个客户端，请求接口，如果401未认证，登陆，然后再去请求

**Comment by 1557100211** [comment]
OK
