### ISSUE TITLE
如何修改项目请求地址

### ISSUE THREAD

**Issue by jiangjunfeng98** [Dreampie/Resty#36]
现在项目要部署到一个内部公共平台上，部署后无法访问。根据以前springMVC项目部署经验要修改ServletRequest中的地址，即
public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain){
request.setAttribute("ctx", "");
request.setAttribute("ctx_url", "/");
chain.doFilter(request, response);
}

想要的结果是，本地tds.war包扔到tomcat下，访问地址为：123.1.1.123:80/tds，现在部署到平台上后访问地址为：10.1.1.3:80,我无权修改配置，只能改代码

**Comment by Dreampie** [comment]
在filter的路径修改为 `/tds/*`

**Comment by jiangjunfeng98** [comment]
web.xml
<display-name>tds</display-name>
    <filter>
        <filter-name>RestyFilter</filter-name>
        <filter-class>cn.dreampie.route.RestyFilter</filter-class>
        <init-param>
            <param-name>exclusions</param-name>
            <param-value>                /**/*.html,/**/*.js,/**/*.map,/**/*.gif,/**/*.jpg,/**/*.png,/**/*.css,/**/*.ico,/druid/**,/**/*.ttf,/**/*.woff,/**/*.woff2
            </param-value>
        </init-param>
        <init-param>
            
            <param-name>configClass</param-name>
            <param-value>com.xxxx.tds.config.AppConfig</param-value>
        </init-param>
    </filter>
    <filter-mapping>
        <filter-name>RestyFilter</filter-name>
        <url-pattern>/tds/*</url-pattern>
    </filter-mapping>

是这样吗？改了一样无效

**Comment by jiangjunfeng98** [comment]
web.xml
`<display-name>tds</display-name>`
`<filter>`
&emsp;&emsp;`<filter-name>RestyFilter</filter-name>`
&emsp;&emsp;`<filter-class>cn.dreampie.route.RestyFilter</filter-class>`
&emsp;&emsp;`<init-param>`
&emsp;&emsp;&emsp;&emsp;`<param-name>exclusions</param-name>`
&emsp;&emsp;&emsp;&emsp;`<param-value>`
                `/**/*.html,/**/*.js,/**/*.map,/**/*.gif,/**/*.jpg,/**/*.png,/**/*.css,/**/*.ico,/druid/**,/**/*.ttf,/**/*.woff,/**/*.woff2`
&emsp;&emsp;&emsp;&emsp;`</param-value>`
&emsp;&emsp;`</init-param>`
&emsp;&emsp; `<init-param>`
&emsp;&emsp;&emsp;&emsp;`<!--Resty的核心配置文件，需要自己编写一个Config的java文件，并继承Config类-->`
&emsp;&emsp;&emsp;&emsp;`<param-name>configClass</param-name>`
&emsp;&emsp;&emsp;&emsp;`<param-value>com.travelsky.tds.config.AppConfig</param-value>`
&emsp;&emsp;`</init-param>`
&emsp;`</filter>`
&emsp;`<filter-mapping>`
&emsp;&emsp;&emsp;&emsp;`<filter-name>RestyFilter</filter-name>`
&emsp;&emsp;&emsp;&emsp;`<url-pattern>/tds/*</url-pattern>`
&emsp;`</filter-mapping>`

是这样吗？改了还是无效果。我想的是扔到Tomcat下，不用加项目名就可以直接访问

**Comment by Dreampie** [comment]
那你通过nginx转呢
