### ISSUE TITLE
多数据源有没有具体的demo,一个类中如何解决

### ISSUE THREAD

**Issue by zhiyin369love** [Dreampie/Resty#37]
多数据源有没有具体的demo,一个类中如何解决跨库事务问题，

**Comment by Dreampie** [comment]
1.什么情况下的多数据源  一个model 对应两个不同的数据库？
1.2.0-snapshot中  `model.useDSM("数据源名称")` 可以切换model使用不同的数据源
2.多数据源的事务在readme第4点有说到
```
 @Transaction(name = {"default", "demo"}) //多数据源的事务,name填写数据源name，如果你只有一个数据库  直接@Transaction 不需要参数 在Resource的方法上🎍
```
