### ISSUE TITLE
关于权限拦截及过滤器

### ISSUE THREAD

**Issue by jiangjunfeng98** [Dreampie/Resty#38]
登录后访问接口如何获取当前用户信息（Session？），用户访问接口时怎么判断登录信息是否失效进行权限拦截（只能在getAllCredentials？）？

**Comment by Dreampie** [comment]
resty-security 完成整个权限处理过程，可以看源码，getAllCredentials 只是获取所有需要权限的列表和用户的权限列表做对比

**Comment by jiangjunfeng98** [comment]
换句话说就是如果我把除了登录接口外的地址放这里，就能做到用户必须登录的限制了？
获取当前用户信息呢，Session那个有时候不管用

**Comment by Dreampie** [comment]
嗯 是的，凡是需要登录后访问，都放这儿，就能限制权限

**Comment by jiangjunfeng98** [comment]
那我的跳转卸载哪个位置?就是没权限跳到登录界面的跳转操作

**Comment by Dreampie** [comment]
rest都是接口型的 不会跳转 只会返还未登录状态  前端自己处理

**Comment by jiangjunfeng98** [comment]
现在我遇到的最严重的问题，获取当前用户信息呢，request.unwrap那个有时候不管用

**Comment by Dreampie** [comment]
使用Subject对象来获取

**Comment by jiangjunfeng98** [comment]
谢谢，我看到源码了
