### ISSUE TITLE
解析json 参数 在Idea运行成功 生成war后用Tomcat运行 返回503!

### ISSUE THREAD

**Issue by teamGodEater** [Dreampie/Resty#39]
不能贴图吗!!!
![1](https://cloud.githubusercontent.com/assets/18326706/16300391/59fe80de-3972-11e6-90b1-cf75a0ab74ab.png)
![2](https://cloud.githubusercontent.com/assets/18326706/16300392/5a04ed7a-3972-11e6-87d8-098cdb16302b.png)
![log](https://cloud.githubusercontent.com/assets/18326706/16300393/5a32be58-3972-11e6-823e-e37e6cf327d3.png)

**Comment by teamGodEater** [comment]
在idea 运行 都是直接就 通过了! 生成war 后就出错了

**Comment by teamGodEater** [comment]
![33](https://cloud.githubusercontent.com/assets/18326706/16300528/f8d25ee2-3972-11e6-8bda-30ba02f9f890.png)
这个是代码

**Comment by Dreampie** [comment]
错误信息

**Comment by Dreampie** [comment]
如果还有问题请reopen这个问题
