### ISSUE TITLE
关于Subject取值问题

### ISSUE THREAD

**Issue by jiangjunfeng98** [Dreampie/Resty#43]
请问`Subject.set(key,value)`这种赋值是正对当前用户，还是所有用户？可不可以把`Subject`理解为当前用户的Session？

**Comment by Dreampie** [comment]
嗯，当前用户

**Comment by jiangjunfeng98** [comment]
在多线程里面，怎么取到Subject呢？
进行批量发送邮件的耗时操作，使用了异步，在new Thread操作，但是要告诉用户发送进度和发送失败的信息。
现在我想把进度和错误信息写在了Subject里，然后使用轮询来获取发送进度和错误信息。但是在new Thread的Subject是null

**Comment by Dreampie** [comment]
在创建线程之前 把值取出来传进去

**Comment by Dreampie** [comment]
如果还有问题请reopen这个问题
