### ISSUE TITLE
Resource方法配置@Transaction，不起作用

### ISSUE THREAD

**Issue by zhangyanming** [Dreampie/Resty#44]
代码如下：
`@API("/orderFeedback")`
`public class OrderFeedbackResource extends ApiResource {`
‘@POST("/orderSign")‘’
    ‘’@Transaction’
`public Map orderSign(OrderPositionLog HEAD, OrderSign XML_DATA){`
`//共5条，保存2条后，抛出RuntimeException，数据库中前两条保存进去了。没有起到事务的作用。`
`}`
`}`

AppConfig类
‘interceptorLoader.add(new TransactionInterceptor());’

**Comment by Dreampie** [comment]
方法注解：
```
@Transaction
```
configInterceptor
```
    //事务的拦截器 @Transaction
    interceptorLoader.add(new TransactionInterceptor());
```

**Comment by zhangyanming** [comment]
少贴了几行代码，AppConfig中在configInterceptor方法加了事务拦截器。

**Comment by Dreampie** [comment]
github的文本框左下角有个markdown使用方法，建议看一下

需要进行事务处理的方法，不要在里面catch异常，把异常throw出来，其次保证你的数据库引擎支持事务

**Comment by zhangyanming** [comment]
跟踪TransactionInterceptor的intercept方法执行dsm.rollbackTransaction();方法了，但是数据还是进去了。MySQL用的是InnoDB

**Comment by zhangyanming** [comment]
跟踪：TransactionManager类的rollback()方法
Connection conn = dataSourceMeta.getCurrentConnection();
获取结果是 conn为null

**Comment by Dreampie** [comment]
抱歉，最近比较忙，你在执行sql之前跟踪
![image](https://cloud.githubusercontent.com/assets/3667080/18192154/36530618-7104-11e6-899d-f5809c82fd2f.png)
看看setConnection没有

**Comment by zhangyanming** [comment]
原因找到了，默认数据源的问题，理解成只要一个数据源’@Transaction’就不用加数据源了。
resty的并发测试怎么样？

**Comment by Dreampie** [comment]
一个数据源 的确不用加数据源名称 `@Transaction` 就可以了

**Comment by Dreampie** [comment]
如果还有问题请reopen这个问题
