### ISSUE TITLE
Route method invoke error.

### ISSUE THREAD

**Issue by melonlee** [Dreampie/Resty#49]
请问在进行对象保存操作的时，发生这个错误，其中Sign的字段内容为id,content,u_id,createdate

@API("/sign")
public class SignResource extends ApiResource {
 
    @POST("/save")
    public Map save(Sign sign) {

        //check is submit >5

        System.out.println(sign.toJson());

        Long todayCount = Sign.dao.countBy("t_sign.u_id = ? and TO_DAYS(NOW()) -TO_DAYS(t_sign.createdate) <=1", sign.get("uId"));

        System.out.println("todayCount-->" + todayCount);

        if (null != todayCount && todayCount < 5) {
            //save
            return Maper.of("data", Sign.dao.save());

        } else {
            return Maper.of("code", 500, "msg", "count>5");
        }
    }

Thanks!

**Comment by melonlee** [comment]
@Dreampie debug时发现传入进来的对象sign中的我字段信息都是null（例如uid,content），因为在save()之前还有个sql是通过sign的某个属性进行query,所以还没运行到save()的时候就已经异常了

**Comment by melonlee** [comment]
debug信息： http://ww3.sinaimg.cn/large/775c483fgw1fbgqsmofdcj20q70aewhi.jpg

**Comment by Dreampie** [comment]
怎么传的的 {sign:对象json}？

**Comment by melonlee** [comment]
现在使用的是传统的form post表单方式提交的sign对象，需要{sign:对象json}这样提交吗?

**Comment by Dreampie** [comment]
使用json提交试试
