### ISSUE TITLE
需求Subject.removePrincipal(String username)方法

### ISSUE THREAD

**Issue by jacobzeng** [Dreampie/Resty#53]
遇到的case如下
前提条件
1. 没有启用缓存

流程
1. 更新账户密码,注意并不是更新自己的密码，而是作为管理员更新其他账户的密码
2. 立即使用新账户密码登录失败（只有重启后才能成功）

原因：
检查代码是因为Subject.credentials中有principals的缓存，但是没有找到方法清理principals

请指导一下

**Comment by Dreampie** [comment]
Subject.removeAllCredentials

**Comment by jacobzeng** [comment]
Subject.removeAllCredentials这个用了，但是没达到目的，这个方法只是清理了Credential没有清理Principal，认证的时候是从Principal里面获取的用户信息缓存
暂时自己fork了一个增加了个removePrincipal(String username)

**Comment by Dreampie** [comment]
如果执行了退出的动作是会立即生效，你的操作是这个账户是登录状态，修改了之后再立即去登录？

**Comment by Dreampie** [comment]
注意代码缩进格式 同时 readme加更新说明 pr过来吧
