### ISSUE TITLE
resty-cache-1.3.1-缓存和数据库数据不一致

### ISSUE THREAD

**Issue by tangzhe7** [Dreampie/Resty#57]
![image](https://user-images.githubusercontent.com/10623716/39691379-0d6d75c8-5210-11e8-9b52-d01720c292eb.png)
![image](https://user-images.githubusercontent.com/10623716/39691429-1eebce6c-5210-11e8-9b67-a2e1ab6f76d8.png)
这是我的测试数据

**Comment by Dreampie** [comment]
https://github.com/Dreampie/Resty/blob/master/resty-orm/src/main/java/cn/dreampie/orm/Base.java

![image](https://user-images.githubusercontent.com/3667080/39691975-e3851e12-5211-11e8-865b-80aaad1e0382.png)
麻烦调试一下看看这个清理缓存是否成功

**Comment by zhaoyunfei9271** [comment]
确实不行，insert完成无法查寻数据

**Comment by Dreampie** [comment]
麻烦详细描述一下问题，是更新或者插入之后，缓存没有被删除，导致查询列表的还是原来一样的吗？

**Comment by Dreampie** [comment]
@zhaoyunfei9271  问题已经修复了，可以试试

**Comment by zhaoyunfei9271** [comment]
好的👌
