### ISSUE TITLE
有没有办法拿到cookie.uuid,返回给客户端?然后拦截器判断，虽然已有一套控制.

### ISSUE THREAD

**Issue by yovenny** [Dreampie/Resty#58]

**Comment by Dreampie** [comment]
这是一个问题吗？你把cookie取出来，response回去不就行了吗

**Comment by yovenny** [comment]
en，我就是想知道怎么在resty拿这个cookie？

**Comment by yovenny** [comment]
Subject.current().getSessionKey()  ?

**Comment by T-baby** [comment]
getRequest()然后.getCookieValue(key)

**Comment by yovenny** [comment]
key的值是UserName？

**Comment by yovenny** [comment]
我自己试下先...

**Comment by yovenny** [comment]
@T-baby 拿到Session-Token，后面怎么检测是否已经失效？

**Comment by yovenny** [comment]
@T-baby 拿到Session-Token，后面怎么检测是否已经失效？
看代码貌似不行。
