### ISSUE TITLE
fastcgi 远程命令执行漏洞

### ISSUE THREAD

**Issue by xqc2000** [Dreampie/Resty#59]
fastcgi 1.2.24之前的版本存在远程命令执行漏洞，请更新fastcgi版本。否则调用cn.dreampie.common.util.json.Jsoner的toObject函数的地方都存在远程命令执行

**Comment by Dreampie** [comment]
fastjson吗，我的依赖是 provided 类型的目前是1.2.5，用户自己引入dependency的时候修改版本就好

**Comment by xqc2000** [comment]
建议修改pom文件的fastjson为1.2.24以上的版本，否则用户不清楚的话就会有问题了

**Comment by Dreampie** [comment]
目前的版本是比1.2.24高的，现在是 1.2.5

**Comment by Dreampie** [comment]
Done
